Team04_site/Team04_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('gdrp/', include('gdrp.urls')),
    path('', include('gdrp.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

Team04_site/gdrp/urls.py
from django.urls import path
from . import views
import datetime


app_name = 'gdrp'
urlpatterns = [
    path('', views.HomepageView.as_view(), name="homepage"),
    path('privacy_policy/', views.PrivacyPolicyView.as_view(), name="privacy_policy"),
    path('termsofservice/', views.ToSView.as_view(), name="tos"),
    path('contact/', views.TeamInfoView.as_view(), name='contact'),
    path('about/', views.TeamInfoView.as_view(), name='about'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/driver/', views.DriverDashboardView.as_view(), name='dash_driver'),
    path('promotions/create/', views.PromotionCreateView.as_view(), name='promo_create'),
    path('dashboard/admin/', views.AdminDashboardView.as_view(), name='dash_admin'),
    path('dashboard/sponsor/', views.SponsorDashboardView.as_view(), name='dash_sponsor'),
    path('account/', views.UserInfo.as_view(), name='account_info'),
    path('account/login/', views.UserLoginView.as_view(), name='account_login'),
    path('product/<int:pk>/', views.ProductView.as_view(), name='product'),
    path('add_products/', views.AddProductsFormView.as_view(), name='product_addm'),
    path('remove_products/', views.remove_item_catalog, name="remove_item"),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('user_login/', views.UserLoginView.as_view(), name='user_login'),
    path('driver_login/', views.DriverLoginView.as_view(), name='driver_login'),
    path('sponsor_login/', views.SponsorLoginView.as_view(), name='sponsor_login'),
    path('admin_login/', views.AdminLoginView.as_view(), name='admin_login'),
    path('user_list/', views.AdminUserList.as_view(), name='user_list'),
    path('create_account/', views.CreateAccount.as_view(), name='create_account'),
    path('create_account/driver/', views.CreateDriverAccount.as_view(), name='create_driver'),
    path('create_account/sponsor/', views.CreateSponsorAccount.as_view(), name='create_sponsor'),
    path('create_account/admin/', views.CreateAdminAccount.as_view(), name='create_admin'),
    path('sponsor_create/', views.SponsorCreateView.as_view(), name='sponsor_create'),
    path('sponsor_create/login', views.AdminLoginView.as_view(), name='spc_admin_login'),
    path('catalog/<int:catalog_id>/', views.CatalogView.as_view(), name='catalog'),
    path('edit_catalogs/', views.EditCatalogsView.as_view(), name='edit_catalogs'),
    #path('catalog/<int:catalog_id>/search_tag/<str:query>/', views.CatalogSearchTagView.as_view(), name='catalog_tag_search'),
    #path('catalog/<int:catalog_id>/search_cat/<str:query>/', views.CatalogSearchCatView.as_view(), name='catalog_cat_search'),
    path('ebay_search/', views.EbaySearch.as_view(), name='ebay_search'),
    path('ebay_search/add/', views.AddToCatalog.as_view(), name="add_to_catalog"),
    path('change_pass/', views.ChangePasswordView.as_view(), name='change_pass'),
    path('reports/', views.ReportsView.as_view(), name='reports'),
    path('logs/', views.ReportAndLogView.as_view(), name='reports_logs'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('logout_user/<int:user_id>/', views.logout_user, name='logout_user'),
    path('user_list/add_points/<int:user_id>/', views.add_points, name='add_points'),
    path('user_list/remove_points/<int:user_id>/', views.remove_points, name='remove_points'),
    path('user_list/zero_points/<int:user_id>/', views.zero_points, name='zero_points'),
    path('process_order/<int:order_id>/', views.process_order, name='process_order'),
    path('change_pointc/<int:catalog_id>/', views.change_point_conversion, name='change_point_converion'),
    path('max_points/<int:user_id>/', views.max_points, name='max_points'),
    path('download_logs/', views.download_logs, name='download_logs'),
    path('download-login-attempts/', views.download_login_attempts, name='download_login_attempts'),
    path('download-account-creations/', views.download_account_creations, name='download_account_creations'),
    path('download-password-changes/', views.download_password_changes, name='download_password_changes'),
    path('download-points-removed/', views.download_points_removed, name='download_points_removed'),
    path('download-points-added/', views.download_points_added, name='download_points_added'),
    path('download-application-sent/', views.download_application_sent, name='download_application_sent'),
    path('download-account-deletions/', views.download_account_deletions, name='download_account_deletions'),
    path('download_pdf/', views.download_pdf, name='download_pdf'),
    # path('download-catalog-changes/', views.download_catalog_changes, name ='download_catalog_changes'),
    path('auth/', views.auth, name='auth'),
    path('auth/callback/', views.auth_callback, name='auth_callback'),
    path('quick_pruchase/', views.PurchaseSingleItem.as_view(), name='single_buy'),
    path('add_to_cart/', views.AddToOrder.as_view(), name="add_to_order"),
    path('shopping_cart/', views.Cart.as_view(), name='shoppingcart'),
    path('approve_application/', views.approve_application, name='approve_application'),
    path('download_pdf/<str:filename>/', views.download_pdf, name='download_pdf'),
    path('change_conv_rate/', views.change_conv_rate, name='change_conv_rate'),
]

Team04_site/gdrp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User, Group
from django.http import FileResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from google.oauth2 import id_token
from google.auth.transport.requests import Request
from .models import Product, Category, Catalog, Product_catalog, Promotion, Profile, Order, Order_Details, Application, Sponsor
from .forms import AddProductsForm, AccountCreationForm, DriverCreationForm, AdminCreationForm, SponsorCreationForm, LoginForm, PromoCreateForm, ReportsDriverPointsLogForm, UserInfoUpdateForm
from werkzeug.security import check_password_hash
from django.views.generic.edit import FormView
from django.contrib import messages
#from .audit import log_login_attempts, log_account_creation, log_password_change, log_points_added, log_points_removed, download_logs
from .audit import *
from .ebay_api import EbayAPI
from django.conf import settings
from ebaysdk.trading import Connection as Trading
from ebaysdk.shopping import Connection as Shopping
from .report import *
import requests
import csv
import datetime
import os

# View for inital endpoint
class HomepageView(generic.TemplateView):
    template_name = 'gdrp/Homepage.html'
    context_object_name = 'Homepage'

# to change to Sponsor view (unimplemented)
class ToSView(generic.TemplateView):
    template_name = 'gdrp/termsofservice.html'
    context_object_name = 'Terms of Service'

# view for Privacy policy page
class PrivacyPolicyView(generic.TemplateView):
    template_name = 'gdrp/privacypolicy.html'
    context_object_name = 'Privacy Policy' 

# view for the user dashboard 
class DashboardView(generic.TemplateView):
    template_name = 'gdrp/dashboard.html'
    context_object_name = 'Dashboard'

# page to create a sponsor object
class SponsorCreateView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
    template_name = 'gdrp/create_sponsor.html'
    login_url = 'gdrp:admin_login'
    
    def post(self, request):
        name = request.POST.get('name')
        sponsor = Sponsor.objects.create(name=name)
        sponsor.save()

        return redirect('gdrp:dash_admin')
    
    def test_func(self):
        return self.request.user.groups.filter(name='admin').exists()

class PromotionCreateView(FormView):
    template_name = "gdrp/promotion-Create.html"
    form_class = PromoCreateForm
    #success_url = '.'
    success_url = '.'
    

    # Currently Does not function as intended
    # 

    def form_valid(self, form):
        name = str(form.data.get('name'))
        desc = str(form.data.get('description'))
        mult = float(form.data.get('multiplier'))
        print(name, desc, mult)
        promo = Promotion(name = name, description = desc, multiplier = mult)
        promo.save()
        return super().form_valid(form)

class PromotionListView(LoginRequiredMixin, generic.TemplateView):
    template_name = "gdrp/dash_driver.html"
    login_url = 'gdrp:admin_login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        context['promotion_list'] = profile.promotions.all()
        return context

class AddProductsFormView(generic.FormView):
    template_name = "gdrp/add_multi_products.html"
    form_class = AddProductsForm

    def form_valid(self, form):
        etsy_pids = form.cleaned_data['etsy_pids']
        pid_list = [int(id) for id in etsy_pids.split()]

        cat_id = form.cleaned_data('catalog')
        if (cat_id):
            catalog = Catalog.objects.get(id=cat_id)
        # Use EtsyController to add products to the catalog.

        return super().form_valid(form)

class DriverDashboardView(LoginRequiredMixin, generic.TemplateView):
    template_name = "gdrp/dash_driver.html"
    context_object_name = "Driver Dashboard"
    login_url = 'gdrp:driver_login'
    #promotion_list = 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        
        # Eventually fix the promotions table in the DB
        #context['promotion_list'] = profile.promotions.all()
        context['promotion_list'] = Promotion.objects.all()
        if self.request.method == "POST":
            context['message'] = self.request.POST.get('message')
        return context
    

class AdminDashboardView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
    template_name = "gdrp/dash_admin.html"
    context_object_name = "Admin Dashboard"
    login_url = 'gdrp:admin_login'

    def test_func(self):
        return self.request.user.groups.filter(name='admin').exists()

class SponsorDashboardView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
    template_name = "gdrp/dash_sponsor.html"
    context_object_name = "Sponsor Dashboard"
    login_url = 'gdrp:sponsor_login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        catalogs = Catalog.objects.all()
        applications =  Application.objects.filter(approved=False)
        context['applications'] = applications
        context['catalogs'] = catalogs
        if self.request.method == "POST":
            context['message'] = self.request.POST.get('message')
            
            # create a new application object and save it
            application = Application.objects.create(driver=self.request.user.driver_profile)
            
            # notify the sponsor of the new application
            messages.add_message(self.request, messages.SUCCESS, 'You have a new application to view!')

        return context

    def test_func(self):
        isAdmin = self.request.user.groups.filter(name='admin').exists()
        isSponsor = self.request.user.groups.filter(name='Sponsors').exists()
        return isAdmin or isSponsor

    
class UserInfo(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserInfoUpdateForm
    template_name = 'gdrp/account_info.html'
    context_object_name = 'user'
    success_url = reverse_lazy('gdrp:account_info')
    login_url = 'gdrp:admin_login'

    def get_object(self):
        return self.request.user
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        response =  super().form_valid(form)

        profile = self.object.profile
        profile.phone = int(form.cleaned_data['phone'])
        profile.save()

        return response
    
# view for a specific product 
class ProductView(generic.DetailView):
    model = Product
    template_name = 'gdrp/product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        image = request.FILES.get('image')
        # This updates the image of the product
        # when an admin uploads one.
        if image:
            self.object.image = image
            self.object.save()
        # This updates the stock of the product
        inventory = request.POST.get('inventory')
        if inventory:
            self.object.inventory = int(inventory)
            self.object.save()
            
        category_pk = request.POST.get('category')
        if category_pk:
            category = Category.objects.get(pk=category_pk)
            
            self.object.category = category
            self.object.save()
        return redirect(self.object.get_absolute_url())
        

# view for password reset page
class PasswordReset(generic.TemplateView):
    template_name = "gdrp/password_reset.html"
    context_object_name = "Password Reset"

# view for general user login (unused)
class UserLoginView(generic.TemplateView):
    template_name = "gdrp/user_login.html"
    context_object_name = "User Account Login"

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.user.is_authenticated:
            return redirect('gdrp:dashboard')
        return response

# view for Driver group login
class DriverLoginView(LoginView):
    template_name = "gdrp/Good_Driver.Driver_Login.html"
    context_object_name = "Driver Login"
    form_class = LoginForm

    def form_valid(self, form):
        # user_agent = self.request.META.get('HTTP_USER_AGENT', '')
        username = form.cleaned_data['username']
        user = User.objects.get(username=username)
        if not user:
            form.add_error(None, 'Username not found')
            return self.form_invalid(form)

        ip = None
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')


        if not user.application.approved:
            form.add_error(None, 'Your application has not been approved by your sponsor yet. Please check later.')
            log_login_attempts(self.request.user.id, True, ip)
            return  self.form_invalid(form)

        response = super().form_valid(form)
        if self.request.user.is_authenticated:

Team04_site/gdrp/templates/gdrp/Good_Driver.Sponsor_Login.html
{% extends 'gdrp/base.html' %}
{% load static %}
{% block content %}
<div>
<h1>Welcome to the Sponsor Login Page!</h1>
<p2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Login</button>
</form>
</p2>
</div>

<div class="g-signin2" data-onsuccess="onSignIn"></div>
<script src="https://apis.google.com/js/platform.js" async defer></script>
<meta name="google-signin-client_id" content="'707081518512-efqnpuod4o1aoqnd8un716s67i5g71i3.apps.googleusercontent.com">


<!--Google Sign In Logic-->
<script>
function onSignIn(googleUser) {
    var profile = googleUser.getBasicProfile();
    console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
    console.log('Name: ' + profile.getName());
    console.log('Image URL: ' + profile.getImageUrl());
    console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
  }
</script>

  <a href="#" onclick="signOut();">Sign out</a>
<script>
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      console.log('User signed out.');
    });
  }
</script>
<!--End Google Sign In Logic-->

<p>Forgot password?</p>
<a href="{% url 'gdrp:password_reset' %}"><button>Reset Password</button></a>

<div>
    <a href="{% url 'gdrp:tos' %}">Terms of Service</a><br>
    <a href="{% url 'gdrp:privacy_policy' %}">Privacy Policy</a>
</div>

{% endblock %}

Team04_site/gdrp/templates/gdrp/account.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>Good Driver Incentive Program</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="{% static 'gdrp/style.css' %}" type="text/css" media="screen,projection" />
  
  <style>
    /* Dropdown button */
    .dropbtn {
      display: inline-block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }
    
    /* Dropdown content (hidden by default) */
    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f9f9f9;
      z-index: 1;
    }
    
    /* Links inside the dropdown */
    .dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
      text-align: left;
    }
    
    /* Change color of dropdown links on hover */
    .dropdown-content a:hover {
      background-color: #f1f1f1
    }
    
    /* Show the dropdown menu on hover */
    .dropdown:hover .dropdown-content {
      display: block;
    }
  </style>
</head>

<body>
  <div id="container">
    <div id="header">
      <h1><a href="#">Good Driver Incentive Program</a></h1>
      <h3>We love our drivers!</h3>
    </div>

    <ul id="nav">
      <li><a href="{% url 'gdrp:dashboard' %}" class="active">Home</a></li>
      <li><a href="{% url 'gdrp:about' %}">About</a></li>
      <li><a href="{% url 'gdrp:catalog' 1 %}">Catalog</a></li>
      <li class="dropdown">
        <a href="#" class="dropbtn">Account</a>
        <div class="dropdown-content">
          <a href="{% url 'gdrp:change_pass' %}">Change Password</a>
          <a href="{% url 'gdrp:logout' %}">Logout</a>
          <a href="#">View Account Information</a>
        </div>
      </li> 
      <li><a href="{% url 'gdrp:contact' %}">Contact</a></li>
      <li><a href="{% url 'gdrp:termsofservice'%}">Terms Of Service</a></li>
      <li><a href="{% url 'gdrp:privacypolicy' %}">Privacy Policy</a></li>
      <li><a href="{% url 'gdrp:Good_Driver.Admin_Login' %}">Admin login</a></li>
      <li><a href="{% url 'gdrp:Good_Driver.Driver_Login' %}">Driver login</a></li>
      <li><a href="{% url 'gdrp:Good_Driver.Sponsor_Login' %}">Sponsor login</a></li>
    </ul>

    <br class="clear" />
    
    

    <div id="content">
      <h1><a href="#" id="intro"></a>Vehicle Entry Information</h1>

      <label for="make">Make:</label>
      <input type="text" id="make" name="make">

      <label for="model">Model:</label>
      <input type="text" id="model" name="model">

      <label for="year">Year:</label>
      <input type="number" id="year" name="year" min="1900" max="2099" step="1">

      <label for="color">Color:</label>
      <input type="text" id="color" name="color">

      <label for="mileage">Mileage:</label>
      <input type="number" id="mileage" name="mileage" min="0" max="999999" step="1">
    </div>
    
    <div id="content">
      <h1><a href="#" id="intro"></a>Points Available</h1
  <div id="footer">
  </div>
</body>
</html>

Team04_site/gdrp/templates/gdrp/auditlogdownload.html
{% extends 'gdrp/base.html' %}

{% block content %}
<html>
<head>
    <title>Download Logs or Reports</title>
</head>
<body>
    <h1>Download Logs or Reports</h1>
    <form action="{% url 'gdrp:download_password_changes' %}" method="get">
        {% csrf_token %}
      <label for="login_attempts">Password Changes:</label>
        <select name="report_type">
            <option value="csv">CSV</option>
            <option value="report">Report</option>
        </select>
        <label for="start_date">Start Date:</label>
        <input type="date" name="start_date">
        <label for="end_date">End Date:</label>
        <input type="date" name="end_date">
        <button type="submit">Download Password Changes</button>
    </form>

    <form action="{% url 'gdrp:download_login_attempts' %}" method="get">
        {% csrf_token %}
        <label for="login_attempts">Login Attempts:</label>
        <select name="report_type">
            <option value="csv">CSV</option>
            <option value="report">Report</option>
        </select>
        <label for="start_date">Start Date:</label>
        <input type="date" name="start_date">
        <label for="end_date">End Date:</label>
        <input type="date" name="end_date">
        <button type="submit">Download Login Attempts</button>
    </form>

    <form action="{% url 'gdrp:download_account_creations' %}" method="get">
        {% csrf_token %}
        <label for="account_creations">Account Creations:</label>
        <select name="report_type">
            <option value="csv">CSV</option>
            <option value="report">Report</option>
        </select>
        <label for="start_date">Start Date:</label>
        <input type="date" name="start_date">
        <label for="end_date">End Date:</label>
        <input type="date" name="end_date">
        <button type="submit">Download Account Creations</button>
    </form>

    <form action="{% url 'gdrp:download_application_sent' %}" method="get">
        {% csrf_token %}
        <label for="application_sent">Application Sent:</label>
        <select name="report_type">
            <option value="csv">CSV</option>
            <option value="report">Report</option>
        </select>
        <label for="start_date">Start Date:</label>
        <input type="date" name="start_date">
        <label for="end_date">End Date:</label>
        <input type="date" name="end_date">
        <button type="submit">Download Application Sent</button>
    </form>

    <form action="{% url 'gdrp:download_account_deletions' %}" method="get">
        {% csrf_token %}
        <label for="account_deletions">Account Deletions:</label>
        <select name="report_type">
            <option value="csv">CSV</option>
            <option value="report">Report</option>
        </select>
        <label for="start_date">Start Date:</label>
        <input type="date" name="start_date">
        <label for="end_date">End Date:</label>
        <input type="date" name="end_date">
        <button type="submit">Download Account Deletions</button>
    </form>

    <form action="{% url 'gdrp:download_pdf' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="filename" value="{{ item.id }}.pdf">
        <button type="submit">Download PDF</button>
    </form>

</body>
</html>
{% endblock %}

Team04_site/gdrp/templates/gdrp/catalog.html
{% extends 'gdrp/base.html'%}
{% load auth_extras %}
{% block content %}

{% if messages %}
    {% for message in messages %}
    <div class="alert alert0{{ message.tags }} alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
{% endif %}

<form action="{% url 'gdrp:catalog' catalog.id %}"method="GET">
    {% csrf_token %}
    <label for="search">Search:</label>
    <input type="text" name="q" value="" placeholder="Search Catalog">
    <input type="submit" value="Filter">
</form>

<div class="item-list">
<ul>
{% for product in products %}
    <li class="item-list">
        <h3>{{ product.name }}</h3>
        {% if product.image %}
            <img src="{{ product.image }}" alt="{{ product.name }}">
        {% endif %}
        <h3>{{ product.id }}</h3>
        <p>{{ product.catagories }}</p>
        <p>{{ product.price_points }}</p>

        <form action="{% url 'gdrp:product' product.id %}" method="GET">
            {% csrf_token %}
            <button type="submit" class="item-list">View</button>
        </form>

        {% if user|has_group:"Sponsors" %}
        <form method="POST" action="{% url 'gdrp:remove_item' %}">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{ product.id }}">
            <input type="hidden" name="cat_id" value="{{ catalog.id }}">
            <input type="hidden" name="next" value="{{ request.path }}?page={{ current_page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
            <button type="submit" class="item-list">Remove Item</button>
        </form>
        {% endif %}

        <form method="POST" action="{% url 'gdrp:single_buy' %}">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{ product.id }}">
            <input type="hidden" name="next" value="{{ request.path }}?page={{ current_page }}{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}">
            <button type="submit" class="item-list">Instant Purchase</button>
        </form>
    </li>

{% empty %}
    <li> no products </li>
{% endfor %}
</ul>
</div>

<br class="clear" />

<div class="fixed-bottom" aria-label="Catalog pagination">
    <span class="pagination justify-content-center">
        <ul class="page-item">
        {% if products.has_previous %}
            <li class="page-item"><a class="pagination-action" href="?page=1{% if request.GET.q %}&q={{ request.GET.q}}{% endif %}">&laquo; first</a></li>
            <li class="page-item"><a class="pagination-action" href="?page={{ products.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a></li>
        {% endif %}

        <li class="current">
            Page {{ products.number }} of {{ products.paginator.num_pages }}.
        </li>

        {% if products.has_next %}
            <li class="page-item"><a class="pagination-action" href="?page={{ products.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a></li>
            <li class="page-item"><a class="pagination-action" href="?page={{ products.paginator.num_pages}}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">last &raquo;</a></li>
        {% endif %}
        </ul>
    </span>
</div>

{% endblock %}

Team04_site/gdrp/templates/gdrp/dash_admin.html
{% extends 'gdrp/base.html' %}
{% load auth_extras %}
  {% block content %}
    <div class="content">
        {% if user.is_authenticated %}
                <h1>Hello Admin</h1>
                {% if message %}
                <p>{{ message }}</p>
                {% endif %}
                <h3>Download Logs</h3>
                <form action="{% url 'gdrp:download_logs' %}" method="get">
                    <label for="start_date">Start date:</label>
                    <input type="date" id="start_date" name="start_date">

                    <label for="end_date">End date:</label>
                    <input type="date" id="end_date" name="end_date">
                    <button type="submit">Download Logs</button>
                </form>
                <form action="{% url 'gdrp:download_login_attempts' %}" method="get">
                    <label for="start_date">Start date:</label>
                    <input type="date" id="start_date" name="start_date">

                    <label for="end_date">End date:</label>
                    <input type="date" id="end_date" name="end_date">
                    <button type="submit">Download Login Attempts</button>
                </form>
                <form action="{% url 'gdrp:download_account_creations' %}" method="get">
                    <label for="start_date">Start date:</label>
                    <input type="date" id="start_date" name="start_date">

                    <label for="end_date">End date:</label>
                    <input type="date" id="end_date" name="end_date">
                    <button type="submit">Download Account Creation Logs</button>
                </form>
                <form action="{% url 'gdrp:download_password_changes' %}" method="get">
                    <label for="start_date">Start date:</label>
                    <input type="date" id="start_date" name="start_date">

                    <label for="end_date">End date:</label>
                    <input type="date" id="end_date" name="end_date">
                    <button type="submit">Download Password Changes</button>
                </form>
        {% endif %}
            <p>Welcome, {{ user.username }}</p>
    </div>

    <h1>Welcome to the Good Driver Rewards Program</h1>
    {% if user.is_authenticated %}
        <p>Hello, {{user.first_name}} {{user.last_name}}</p>
    {% else %}
    <p>This is a short summary of the Good Driver Rewards Program</p>
    {% endif %}

    <form method="GET" action="{% url 'gdrp:dash_driver' %}">
        <button type="submit">Driver view</button>
    </form>
    <form method="GET" action="{% url 'gdrp:dash_sponsor' %}">
        <button type="submit">Sponsor view</button>
    </form>

  {% endblock %}